#!/bin/bash

DIR=$(dirname $0)
CMD="$DIR/waldbrand-website.sh"
CLASS="de.waldbrand.app.mapfile.CreateMapfile"

REPO="$DIR/../.."
TBO="$HOME/github/waldbrand/osm-data/emergency-merged.tbo"
TMP="$REPO/tmp-waldbrand"
RULES="$REPO/project/mapfile/rules"

exec "$CMD" "$CLASS" \
    --input "$TBO" \
    --node-db "$TMP/nodes" --way-db "$TMP/ways" \
    --rules "$RULES" --logs logs --output "$REPO/Brandenburg-waldbrand.xmap"
